---
title: "Syndromic Survellance"
author: "LIN"
date: "2026-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# code for forecasting diarrhoea cases among under five children in Malawi using ARIMA model

```{r cars}

install.packages("rio")
install.packages("tidyverse")
install.packages("forecast")
install.packages("here")
install.packages("tseries")



library(forecast) # for forecating the cases
library(tidyverse) # data management 
library(rio) # This package help with  importing data set in more format
library(here) # This package help with file path and directory 
library(tseries) # for changing data frame object to time series object





```

# loading data

```{r pressure, echo=FALSE}

# loading data from 

diarrhoea_df<- import(here("data/Diarrhoea_u5_2023_2025_data.csv")) |> 
  mutate(year=as.Date(year, format="%Y-%B-%M")) # change the column of year to date format 




```



# calculating ARIMA model for forecasting diarrhoea cases among under five children in Malawi

```{r}

# Step 1: Changing the data to  time series is in the correct format
diarrhoea_ts <- ts(diarrhoea_df$cases, start = c(2020, 1), frequency = 12)

# Step 2: Check for missing values
if(anyNA(diarrhoea_ts)) {
  diarrhoea_ts <- na.interp(diarrhoea_ts)  # Interpolates missing values
}

# Step 3: Check stationarity using  Augmented Dickey-Fuller Test
adf_test <- adf.test(diarrhoea_ts)

# viewing results of the adf test
# If p-value > 0.05, data is non-stationary and may require
print(adf_test)

# Step 4: Fit ARIMA model automatically
fit <- auto.arima(
  diarrhoea_ts,
  stepwise = FALSE,   # allows a more exhaustive search
  approximation = FALSE, 
  seasonal = TRUE,    # enables SARIMA detection if data is seasonal
  trace = TRUE        # prints model selection process
)

# view the model summary
summary(fit)

# Step 5: Diagnostic checks
checkresiduals(fit)   # Plots residuals, ACF, and Ljung-Box test

# Step 6: Forecast next 12 periods
future_forecast <- forecast(fit, h = 12)


# Step7: view the forecasted values 
summary(future_forecast)
v
# Step 8: Plot with ggplot2 theme
autoplot(future_forecast) +
  ggtitle("Malawi 12-Month Forecast of Diarrhoea Cases in 2026") +
  xlab("Time") + ylab("Number of Cases") +
  theme_minimal()




```

