---
title: "Prevalence and incidence Codes"
output: html_document
---




```{r}
# installing the required packages


install.packages("tidyverse") # for data management and wranging 
install.packages("here") # for directory path way 
install.packages("rio") # import and exporting data set
install.packages("janitor") # for cleaning data set


library(tidyverse)
library(here)
library(rio)
library(janitor)


```




## loading data set

```{r}

# loading cholera data set 

cholera_data <- import(here("data", "cholera_data_2022.csv")) |> 
  clean_names() |> 
  mutate(date=as.Date(date, format="%Y-%m-%d"))


# loading mid year population data set
mw_population <- import(here("data", "mw_population.csv")) |> 
  clean_names()


```


## Prevalence proportion

```{r}
# Prevalence proportion

# This code will show the calculation of prevalence proportion using Malawi cholera-2022

# cleaning the district names in both data sets to have similar format

cholera_data$district <- str_to_lower(cholera_data$district)

mw_population$district <- str_to_lower(mw_population$district)


# aggregating the cases for first quarter (January to March) 2022
first_quarter <-cholera_data |> 
  filter(date >= "2022-01-01" & date <= "2022-06-30") |> 
  group_by(district) |> 
  summarise(first_quarter_cases=sum(cases, na.rm = TRUE))


# merging the two quarters data of cases columns
first_quarter<- merge(first_quarter, mw_population, by="district")


# calculating prevalence proportion for first quarter for each district

prev_district<- first_quarter |> 
  mutate(prevalence=round((first_quarter_cases/population)*10000,2))


# view the prevalence proportion for each district
print(prev_district)


```







##Incidence Proportion

```{r}

blantyre_incidence<- cholera_data |> 
  filter(district== "blantyre" ) |>
  filter(date >= "2022-01-01" & date <= "2022-06-30") |>
  group_by(district, epiweek) |>
  summarise(first_quarter_cases=sum(cases, na.rm = TRUE))


# merging with population data set
blantyre_incidence <- merge(blantyre_incidence, mw_population, by="district") |> 
  mutate(incidence_prop=round((first_quarter_cases/population)*100000,2)) |> 
  select( district, epiweek, incidence_prop) 

# viewing incidence proportion for Blantyre district per week
blantyre_incidence
  

```



## Incidence Rate

```{r}


Total_days_obs <- 816*21 # 816 days observed for 21 people
Years_obs <- ceiling(Total_days_obs/365)  # The assumption is not a leap year
Incidence_rate <-  (5/Years_obs)*10
print(Incidence_rate) 


```





# Risk Ratio (RR)

```{r}

install.packages("epitools")  # installing the epitools package

## load the epitools package. 
library(epitools) 


# create a data frame with two columns vaccine_state and disease_outcome
df6 <- data.frame(
 vaccine_state= sample(rep(c("Vaccinated", "Unvaccinated"), 20)),   
 disease_outcome= sample(rep(c("Positive", "Negative"), 20)) # 
# print out the first 6 variables from the data set created will use the head() function  

)

# calculating  the risk ratio, the following code line will be used 
riskratio(df6$vaccine_state, df6$disease_outcome)



# calculate the odds ratio 
oddsratio(df6$vaccine_state, df6$disease_outcome)

```



