name: R Quality Checks

on:
  pull_request:
    paths:
      - '**.R'

jobs:
  lint-and-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up R
        uses: r-lib/actions/setup-r@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05 # v2

      - name: Set R_LIBS_USER
        run: echo "R_LIBS_USER=$(Rscript -e 'cat(.libPaths()[1])')" >> $GITHUB_ENV

      - name: Cache R packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install lintr
        run: |
          Rscript -e "install.packages('lintr', repos='https://cran.r-project.org')"


      - name: Annotate lintr warnings
        run: Rscript .github/run_linters.R
