name: PR Workflow File Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan-workflows:
    name: Scan Workflow Changes in PRs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # needed to comment on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find modified workflow files
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed_files.txt
          echo "files=$(cat changed_files.txt | grep '^.github/workflows/' || true)" >> $GITHUB_OUTPUT

      - name: Comment if workflows changed
        if: steps.changes.outputs.files != ''
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: workflow-warning
          message: |
            ⚠️ **Warning: This PR modifies GitHub Actions workflow files.**

            Please review the workflow changes carefully for security risks (e.g., malicious code, secret exfiltration, or unsafe commands).

            Changed files:
            ```
            ${{ steps.changes.outputs.files }}
            ```

      - name: Run actionlint (static analysis)
        if: steps.changes.outputs.files != ''
        run: |
          curl -sSL https://github.com/rhysd/actionlint/releases/latest/download/actionlint_Linux_x86_64.tar.gz \
            | tar xz
          ./actionlint $(echo "${{ steps.changes.outputs.files }}")
