# Book settings
title: "Quality Assurance for Reproducible Analytical Pipelines"
author: ""
# email: 
# logo: "enter_logo"

repository:
  url: https://github.com/ONSdigital/ons-ppt/tree/QA_for_RAP/themes/data_analysis/RAP/QA_for_RAP/
  path_to_book: book
  # branch: main

html:
  home_page_in_navbar: false
  # favicon: ""
  use_repository_button: true
  # extra_navbar: "<p>Book version 2025.1</p><a href='https://www.gov.uk/government/organisations/government-analysis-function' target='_blank'><img src='./_static/af_logo.png' alt='The Government Analysis Function logo' style='width:50%;'></a>"
  # Do we want to add something about it being developed from Duck book??

sphinx:
  extra_extensions:
    - sphinx_tabs.tabs
    - sphinx.ext.todo
  config:
    todo_include_todos: true
    language: en
    html_show_copyright: false
    myst_heading_anchors: 3

latex:
  latex_documents:
    targetname: book.tex
